### ISSUE TITLE
[HELP]: Creating multiple queues in docker compose

### ISSUE THREAD

**Issue by melvingaye** [aertje/cloud-tasks-emulator#108]
Good morning,

This might very well be a PEBKAC situation but wanted to ask anyways. I'm attempting to create multiple queues like so, but my second queue does not get created, instead I see a 404 error for the queue.

> 404 Queue does not exist. If you just created the queue, wait at least a minute for the queue to initialize.

```
services:
  gcloud-tasks-emulator:
    container_name: gcloud-tasks-emulator
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/dev/locations/local/queues/queue1" -queue "projects/dev/locations/local/queues/queue2"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    networks:
      - app-network
  ```

Based on this example, I thought the above would work

```
go run ./ -host localhost \
  -port 8000 \
  -queue projects/dev/locations/here/queues/firstq \
  -queue projects/dev/locations/here/queues/anotherq
```

I also see this output when I run the container

> gcloud-tasks-emulator  | Starting cloud tasks emulator, listening on 0.0.0.0:8123
gcloud-tasks-emulator  | Creating initial queue projects/dev/locations/local/queues/queue1
gcloud-tasks-emulator  | Creating initial queue projects/dev/locations/local/queues/queue2
