### ISSUE TITLE
HTTP Task cannot call localhost

### ISSUE THREAD

**Issue by almen-wong** [aertje/cloud-tasks-emulator#64]
I use the emulator to create HTTP Task
The task is able to GET https://www.google.com, but when I GET http://localhost:8000 the task will fail
Response: `UNKNOWN(2): HTTP status code -1`

this is how I setup the emulator

docker-compose.yml
```
  gcloud-tasks-emulator:
    container_name: gcloud-tasks
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/mysandbox/locations/asia-east1/queues/test"
    ports:
      - "${TASKS_PORT:-8123}:8123"
 ```
 
and this is how i create the task
```
    const client = new CloudTasksClient({
      port: 8123,
      servicePath: "localhost",
      sslCreds: credentials.createInsecure(),
    })

    const parent = client.queuePath(
      "mysandbox",
      "asia-east1",
      "test"
    )
    const task = {
      httpRequest: {
        httpMethod: "GET",
        url: "http://localhost:8000",
      }
    }
   const request = { parent, task }
   await client.createTask(request)
```

any ideas why I cannot call the localhost? I can call http://localhost:8000 directly.
