### ISSUE TITLE
No connection established

### ISSUE THREAD

**Issue by GZLiew** [aertje/cloud-tasks-emulator#89]
HI im trying to use cloud task emulator but my nestjs app keep
throwing the error No connection established

```yml
  cloudtask:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    restart: always
    command: >
      -host localhost -port 8123 
      -queue "projects/core-sandbox/locations/us-central1/queues/push-notifications"
    ports:
      - "8123:8123"
    expose:
      - "8123"
    environment:
      - "APP_ENGINE_EMULATOR_HOST=http://localhost:8080"
```

```ts
const client = new CloudTasksClient({
  port: 8123,
  servicePath: 'localhost',
  sslCreds: credentials.createInsecure(),
});

```
